// Generated by gencpp from file multiple_turtlebot3_cpp/Action1Result.msg
// DO NOT EDIT!


#ifndef MULTIPLE_TURTLEBOT3_CPP_MESSAGE_ACTION1RESULT_H
#define MULTIPLE_TURTLEBOT3_CPP_MESSAGE_ACTION1RESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace multiple_turtlebot3_cpp
{
template <class ContainerAllocator>
struct Action1Result_
{
  typedef Action1Result_<ContainerAllocator> Type;

  Action1Result_()
    : sequence()  {
    }
  Action1Result_(const ContainerAllocator& _alloc)
    : sequence(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _sequence_type;
  _sequence_type sequence;





  typedef boost::shared_ptr< ::multiple_turtlebot3_cpp::Action1Result_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::multiple_turtlebot3_cpp::Action1Result_<ContainerAllocator> const> ConstPtr;

}; // struct Action1Result_

typedef ::multiple_turtlebot3_cpp::Action1Result_<std::allocator<void> > Action1Result;

typedef boost::shared_ptr< ::multiple_turtlebot3_cpp::Action1Result > Action1ResultPtr;
typedef boost::shared_ptr< ::multiple_turtlebot3_cpp::Action1Result const> Action1ResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::multiple_turtlebot3_cpp::Action1Result_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::multiple_turtlebot3_cpp::Action1Result_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::multiple_turtlebot3_cpp::Action1Result_<ContainerAllocator1> & lhs, const ::multiple_turtlebot3_cpp::Action1Result_<ContainerAllocator2> & rhs)
{
  return lhs.sequence == rhs.sequence;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::multiple_turtlebot3_cpp::Action1Result_<ContainerAllocator1> & lhs, const ::multiple_turtlebot3_cpp::Action1Result_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace multiple_turtlebot3_cpp

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::multiple_turtlebot3_cpp::Action1Result_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::multiple_turtlebot3_cpp::Action1Result_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::multiple_turtlebot3_cpp::Action1Result_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::multiple_turtlebot3_cpp::Action1Result_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multiple_turtlebot3_cpp::Action1Result_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multiple_turtlebot3_cpp::Action1Result_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::multiple_turtlebot3_cpp::Action1Result_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b81e37d2a31925a0e8ae261a8699cb79";
  }

  static const char* value(const ::multiple_turtlebot3_cpp::Action1Result_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb81e37d2a31925a0ULL;
  static const uint64_t static_value2 = 0xe8ae261a8699cb79ULL;
};

template<class ContainerAllocator>
struct DataType< ::multiple_turtlebot3_cpp::Action1Result_<ContainerAllocator> >
{
  static const char* value()
  {
    return "multiple_turtlebot3_cpp/Action1Result";
  }

  static const char* value(const ::multiple_turtlebot3_cpp::Action1Result_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::multiple_turtlebot3_cpp::Action1Result_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result definition\n"
"int32[] sequence\n"
;
  }

  static const char* value(const ::multiple_turtlebot3_cpp::Action1Result_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::multiple_turtlebot3_cpp::Action1Result_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sequence);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Action1Result_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::multiple_turtlebot3_cpp::Action1Result_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::multiple_turtlebot3_cpp::Action1Result_<ContainerAllocator>& v)
  {
    s << indent << "sequence[]" << std::endl;
    for (size_t i = 0; i < v.sequence.size(); ++i)
    {
      s << indent << "  sequence[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.sequence[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MULTIPLE_TURTLEBOT3_CPP_MESSAGE_ACTION1RESULT_H
