// Generated by gencpp from file multiple_turtlebot3_cpp/Interruption.msg
// DO NOT EDIT!


#ifndef MULTIPLE_TURTLEBOT3_CPP_MESSAGE_INTERRUPTION_H
#define MULTIPLE_TURTLEBOT3_CPP_MESSAGE_INTERRUPTION_H

#include <ros/service_traits.h>


#include <multiple_turtlebot3_cpp/InterruptionRequest.h>
#include <multiple_turtlebot3_cpp/InterruptionResponse.h>


namespace multiple_turtlebot3_cpp
{

struct Interruption
{

typedef InterruptionRequest Request;
typedef InterruptionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Interruption
} // namespace multiple_turtlebot3_cpp


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::multiple_turtlebot3_cpp::Interruption > {
  static const char* value()
  {
    return "d2b66836810c2e291e1415e0336b0719";
  }

  static const char* value(const ::multiple_turtlebot3_cpp::Interruption&) { return value(); }
};

template<>
struct DataType< ::multiple_turtlebot3_cpp::Interruption > {
  static const char* value()
  {
    return "multiple_turtlebot3_cpp/Interruption";
  }

  static const char* value(const ::multiple_turtlebot3_cpp::Interruption&) { return value(); }
};


// service_traits::MD5Sum< ::multiple_turtlebot3_cpp::InterruptionRequest> should match
// service_traits::MD5Sum< ::multiple_turtlebot3_cpp::Interruption >
template<>
struct MD5Sum< ::multiple_turtlebot3_cpp::InterruptionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::multiple_turtlebot3_cpp::Interruption >::value();
  }
  static const char* value(const ::multiple_turtlebot3_cpp::InterruptionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::multiple_turtlebot3_cpp::InterruptionRequest> should match
// service_traits::DataType< ::multiple_turtlebot3_cpp::Interruption >
template<>
struct DataType< ::multiple_turtlebot3_cpp::InterruptionRequest>
{
  static const char* value()
  {
    return DataType< ::multiple_turtlebot3_cpp::Interruption >::value();
  }
  static const char* value(const ::multiple_turtlebot3_cpp::InterruptionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::multiple_turtlebot3_cpp::InterruptionResponse> should match
// service_traits::MD5Sum< ::multiple_turtlebot3_cpp::Interruption >
template<>
struct MD5Sum< ::multiple_turtlebot3_cpp::InterruptionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::multiple_turtlebot3_cpp::Interruption >::value();
  }
  static const char* value(const ::multiple_turtlebot3_cpp::InterruptionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::multiple_turtlebot3_cpp::InterruptionResponse> should match
// service_traits::DataType< ::multiple_turtlebot3_cpp::Interruption >
template<>
struct DataType< ::multiple_turtlebot3_cpp::InterruptionResponse>
{
  static const char* value()
  {
    return DataType< ::multiple_turtlebot3_cpp::Interruption >::value();
  }
  static const char* value(const ::multiple_turtlebot3_cpp::InterruptionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MULTIPLE_TURTLEBOT3_CPP_MESSAGE_INTERRUPTION_H
