// Generated by gencpp from file multiple_turtlebot3_cpp/InterruptionResponse.msg
// DO NOT EDIT!


#ifndef MULTIPLE_TURTLEBOT3_CPP_MESSAGE_INTERRUPTIONRESPONSE_H
#define MULTIPLE_TURTLEBOT3_CPP_MESSAGE_INTERRUPTIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace multiple_turtlebot3_cpp
{
template <class ContainerAllocator>
struct InterruptionResponse_
{
  typedef InterruptionResponse_<ContainerAllocator> Type;

  InterruptionResponse_()
    : message()
    , success(false)
    , time(0.0)  {
    }
  InterruptionResponse_(const ContainerAllocator& _alloc)
    : message(_alloc)
    , success(false)
    , time(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;

   typedef uint8_t _success_type;
  _success_type success;

   typedef double _time_type;
  _time_type time;





  typedef boost::shared_ptr< ::multiple_turtlebot3_cpp::InterruptionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::multiple_turtlebot3_cpp::InterruptionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct InterruptionResponse_

typedef ::multiple_turtlebot3_cpp::InterruptionResponse_<std::allocator<void> > InterruptionResponse;

typedef boost::shared_ptr< ::multiple_turtlebot3_cpp::InterruptionResponse > InterruptionResponsePtr;
typedef boost::shared_ptr< ::multiple_turtlebot3_cpp::InterruptionResponse const> InterruptionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::multiple_turtlebot3_cpp::InterruptionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::multiple_turtlebot3_cpp::InterruptionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::multiple_turtlebot3_cpp::InterruptionResponse_<ContainerAllocator1> & lhs, const ::multiple_turtlebot3_cpp::InterruptionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.message == rhs.message &&
    lhs.success == rhs.success &&
    lhs.time == rhs.time;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::multiple_turtlebot3_cpp::InterruptionResponse_<ContainerAllocator1> & lhs, const ::multiple_turtlebot3_cpp::InterruptionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace multiple_turtlebot3_cpp

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::multiple_turtlebot3_cpp::InterruptionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::multiple_turtlebot3_cpp::InterruptionResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::multiple_turtlebot3_cpp::InterruptionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::multiple_turtlebot3_cpp::InterruptionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multiple_turtlebot3_cpp::InterruptionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multiple_turtlebot3_cpp::InterruptionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::multiple_turtlebot3_cpp::InterruptionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a515a6e726c8218d87251f2bbce5ccb4";
  }

  static const char* value(const ::multiple_turtlebot3_cpp::InterruptionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa515a6e726c8218dULL;
  static const uint64_t static_value2 = 0x87251f2bbce5ccb4ULL;
};

template<class ContainerAllocator>
struct DataType< ::multiple_turtlebot3_cpp::InterruptionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "multiple_turtlebot3_cpp/InterruptionResponse";
  }

  static const char* value(const ::multiple_turtlebot3_cpp::InterruptionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::multiple_turtlebot3_cpp::InterruptionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string message\n"
"bool success\n"
"float64 time\n"
;
  }

  static const char* value(const ::multiple_turtlebot3_cpp::InterruptionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::multiple_turtlebot3_cpp::InterruptionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.message);
      stream.next(m.success);
      stream.next(m.time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct InterruptionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::multiple_turtlebot3_cpp::InterruptionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::multiple_turtlebot3_cpp::InterruptionResponse_<ContainerAllocator>& v)
  {
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "time: ";
    Printer<double>::stream(s, indent + "  ", v.time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MULTIPLE_TURTLEBOT3_CPP_MESSAGE_INTERRUPTIONRESPONSE_H
